# see https://www.mkdocs.org/user-guide/configuration/ for more config options

site_name: Hyperledger Indy SDK
# site_url: https://docs.sovrin.org/sdk
repo_url: http://github.com/michaeldboyd/indy-sdk/
edit_uri: edit/mkdocs-test/doc/
nav:
- Indy-SDK: 'index.md'
- Test Design: 'test-design.md'
docs_dir: 'doc/'
use_directory_urls: false
dev_addr: '127.0.0.1:8001'
site_dir: '/home/mdb/code/sov/docs-site/sdk/'

markdown_extensions:
  - toc:
      permalink: "#"
theme: readthedocs