# see https://www.mkdocs.org/user-guide/configuration/ for more config options

site_name: Hyperledger Indy SDK
# site_url: https://docs.sovrin.org/sdk
repo_url: http://github.com/michaeldboyd/indy-sdk/
repo_name: 'Indy-SDK'
# edit_uri:
nav:
- Indy-SDK: 'index.md'
- Test Design: 'test-design.md'
docs_dir: 'doc/'
site_dir: 

markdown+extensions:
  - toc:
    permalink: "#"
theme: 
  name: readthedocs
  custom_dir: custom_theme
